In [31]:
#implementation of feedforward network in python 




import numpy as np
inputs=[0.1,0.3,0.5]     #input layer
weights_1=[[0.2,0.4,0.5],                    #weights of layer 1
           [0.3,0.7,0.1],
           [0.2,0.6,0.9]
          ]
weights_2=[[0.4,0.6,0.1],
           [0.2,0.7,0.3],                         #weights of layer 2
           [0.8,0.1,0.5]
          ]
weights_3=[[0.2,0.5,0.3],                      #weights of layer 3
           [0.4,0.6,0.6],
           [0.1,0.9,0.7]
          ]

b1,b2,b3=[0.1,0.1,0.1]                    # bias of layer 1 2 and 3

In [18]:
layer1=np.dot(inputs,weights_1)         #product of layer 1

In [32]:
l1=layer1+b1                          #add bias with layer1

In [17]:
l1

array([0.41, 0.75, 0.73])

In [33]:
output1=[max(0,l1[0]),max(0,l1[1]),max(0,l1[2])]                 # using activation function 

In [20]:
output1

[0.41000000000000003, 0.75, 0.73]

In [21]:
layer_2=np.dot(output1,weights_2)                 #product of  output1 with weights 2

In [23]:
l2=layer_2 + b2

In [24]:
l2

array([0.998, 0.944, 0.731])

In [34]:
output2=[max(0,l2[0]),max(0,l2[1]),max(0,l2[2])]             # using activation function

In [26]:
output2

[0.998, 0.9439999999999998, 0.731]

In [35]:
layer_3=np.dot(output2,weights_3)                      #product of  output2 with weights 3

In [28]:
l3=layer_3 + b3
l3

array([0.7503, 1.8233, 1.4775])

In [37]:
output3=[max(0,l3[0]),max(0,l3[1]),max(0,l3[2])]             # using activation functionoutput3                                                