In [ ]:
import numpy as np

In [1]:
matrix1=np.array([[1,3,4,5],
               [3,5,6,7],
               [3,4,5,6]]
               )

NameError: name 'np' is not defined

In [3]:
matrix1

array([[1, 3, 4, 5],
       [3, 5, 6, 7],
       [3, 4, 5, 6]])

In [4]:
matrix1[1,2]

6

In [5]:
matrix1[:]

array([[1, 3, 4, 5],
       [3, 5, 6, 7],
       [3, 4, 5, 6]])

In [6]:
matrix1[1:3]

array([[3, 5, 6, 7],
       [3, 4, 5, 6]])

In [8]:
matrix1[-1]

array([3, 4, 5, 6])

In [10]:
matrix1[:,:]

array([[1, 3, 4, 5],
       [3, 5, 6, 7],
       [3, 4, 5, 6]])

In [11]:
matrix1[:,1:2]

array([[3],
       [5],
       [4]])

In [12]:
matrix1.size

12

In [13]:
matrix1.shape

(3, 4)

In [14]:
np.max(matrix1)

7

In [16]:
np.min(matrix1)

1

In [18]:
np.var(matrix1)

2.555555555555556

In [19]:
np.std(matrix1)

1.5986105077709065

In [20]:
np.mean(matrix1,axis=0)

array([2.33333333, 4.        , 5.        , 6.        ])

In [33]:
### reshape of matrix

In [21]:
matrix1.reshape(2,6)

array([[1, 3, 4, 5, 3, 5],
       [6, 7, 3, 4, 5, 6]])

In [23]:
### matrix tranpos 

matrix1.T
matrix2=np.array([[1,2,3],
                [3,4,5],
                [4,5,6]])
matrix3=np.array([[1,2,3],
                [3,4,5],
                [4,5,6]])

In [27]:
np.linalg.det(matrix2)

0.0

In [29]:
np.dot(matrix3,matrix2)

array([[19, 25, 31],
       [35, 47, 59],
       [43, 58, 73]])

In [30]:
np.add(matrix3,matrix2)

array([[ 2,  4,  6],
       [ 6,  8, 10],
       [ 8, 10, 12]])

In [31]:
np.subtract(matrix3,matrix2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

now using in neural network

In [35]:
weight=[2,5,4,1,3,7,4]
inputs=[[1,2,3,4,5,3,2],
        [4,7,8,3,5,6,8],
        [3,2,4,6,7,]
       ]
bias=3

In [36]:
product=np.dot(weight,inputs)

ValueError: shapes (7,) and (3,7) not aligned: 7 (dim 0) != 3 (dim 0)