In [1]:
import numpy as np

In [2]:
matrix1=np.array([[1,3,4,5],
               [3,5,6,7],
               [3,4,5,6]]
               )

In [3]:
matrix1

array([[1, 3, 4, 5],
       [3, 5, 6, 7],
       [3, 4, 5, 6]])

In [4]:
matrix1[1,2]

6

In [5]:
matrix1[:]

array([[1, 3, 4, 5],
       [3, 5, 6, 7],
       [3, 4, 5, 6]])

In [6]:
matrix1[1:3]

array([[3, 5, 6, 7],
       [3, 4, 5, 6]])

In [7]:
matrix1[-1]

array([3, 4, 5, 6])

In [8]:
matrix1[:,:]

array([[1, 3, 4, 5],
       [3, 5, 6, 7],
       [3, 4, 5, 6]])

In [9]:
matrix1[:,1:2]

array([[3],
       [5],
       [4]])

In [10]:
matrix1.size

12

In [11]:
matrix1.shape

(3, 4)

In [12]:
np.max(matrix1)

7

In [13]:
np.min(matrix1)

1

In [14]:
np.var(matrix1)

2.555555555555556

In [15]:
np.std(matrix1)

1.5986105077709065

In [16]:
np.mean(matrix1,axis=0)

array([2.33333333, 4.        , 5.        , 6.        ])

In [17]:
### reshape of matrix

In [18]:
matrix1.reshape(2,6)

array([[1, 3, 4, 5, 3, 5],
       [6, 7, 3, 4, 5, 6]])

In [21]:
### matrix tranpos 

matrix1.T


array([[1, 3, 3],
       [3, 5, 4],
       [4, 6, 5],
       [5, 7, 6]])

In [22]:
np.linalg.det(matrix2)

0.0

In [23]:
matrix2=np.array([[1,2,3],
                [3,4,5],
                [4,5,6]])
matrix3=np.array([[1,2,3],
                [3,4,5],
                [4,5,6]])

np.dot(matrix3,matrix2)

array([[19, 25, 31],
       [35, 47, 59],
       [43, 58, 73]])

In [24]:
np.add(matrix3,matrix2)

array([[ 2,  4,  6],
       [ 6,  8, 10],
       [ 8, 10, 12]])

In [25]:
np.subtract(matrix3,matrix2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])